INGREDIENT_NAME_MAX_LENGTH = 200
INGREDIENT_UNIT_MAX_LENGTH = 200
MAX_COOKING_TIME_IN_MIN = 1440
MAX_INGREDIENT_AMOUNT = 10000
MIN_COOKING_TIME_IN_MIN = 1
MIN_INGREDIENT_AMOUNT = 1
RECIPE_NAME_MAX_LENGTH = 200
TAG_NAME_MAX_LENGTH = 200
