# Generated by Django 2.2.19 on 2023-07-07 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20230701_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Проверьте, что название начинается с заглавной буквы и не содержит иных символов, кроме дефиса, нижнего подчеркивания и пробела', regex='^[А-Я][а-яё\\s_-]+$')], verbose_name='Название рецепта'),
        ),
    ]
