# Generated by Django 2.2.19 on 2023-07-08 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230707_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[А-Яа-яЁё]+$')], verbose_name='Название рецепта'),
        ),
    ]
