# Generated by Django 2.2.19 on 2023-07-08 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20230708_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Проверьте, что название начинается с буквы и и не содержит иных символов, кроме дефиса нижнего подчеркивания и пробела', regex='^[А-Яа-яЁё][а-яё\\s_-]+$')], verbose_name='Название рецепта'),
        ),
    ]
